openapi: 3.0.0
info:
  title: Title of the application
  description: >-
    <b>Description of the application</b>
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /api/ndc/v1/aa/{orderCancel}:
    post:
      tags:
        - OrderCancel API
      summary: Order Cancel
      description: >-
        <b>OrderCancel API description</b>
      requestBody:
        required: true
        content:
          'application/json':
            schema:
              type: object
            example:
              gds_code: 26
              ndc_params:
                order_id: AA001HHRGXTA7
                refund_amount: 0
      parameters:
        - name: orderCancel
          in: path
          schema:
            type: string
            readOnly: true
            example: order_cancel
          required: true
      responses:
        '200':
          description: Successful response
          content:
            # application/json: {}
            application/json:
              schema:
                type: object
              example:
                gds_pnr: ''
                carrier_pnr: ''
                is_success: true
                canceled_pnr: ''
                ticket_doc_infos:
                  - ticket_documents:
                      - coupon_infos:
                          - status: V
                  - ticket_documents:
                      - coupon_infos:
                          - status: V
                  - ticket_documents:
                      - coupon_infos:
                          - status: V      